sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- chmod +x ".script/travis-push.sh"
- gem install bundler
- export SFDX_CONSUMERKEY=3MVG92u_V3UMpV.i2DsjLwz7NPFkwKNt8cOBnfSBmbhvel3y5Mt1lHWWyPslCiwiISgjDbqVFRQ==
- export SFDX_USERNAME=test-q5z6zouooks9@example.com
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version 
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $SFDX_CONSUMERKEY --jwtkeyfile assets/server.key --username $SFDX_USERNAME --setdefaultdevhubusername -a mara-v2 --instanceurl https://test.salesforce.com



script:
- sfdx force:mdapi:retrieve -k ./package/package.xml -r ./mdapioutput -u test-q5z6zouooks9@example.com  
#--json
#- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 2
#- sfdx force:org:display -u ciorg
#- sfdx force:source:push -u ciorg
#- sfdx force:apex:test:run -u ciorg --wait 10
#- sfdx force:org:delete -u ciorg -p

after_success:
- sh .script/travis-push.sh
-  git config --global user.email "juraj.ciljak@gmail.com"
-  git config --global user.name "JurajCiljak"
- git config --global --list 
- git add --all
- git status
- git commit -m "Travis update:2019_04_04" -m "master"
- git remote set-url origin https://JurajCiljak:210286Cj@github.com/JurajCiljak/sfdx-travisci-receive.git
- git push origin master 

